repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.3
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args: [--check]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        files: ^textual_cli_agent/
        additional_dependencies: [types-requests]
        args: [--strict, -p, textual_cli_agent]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: pytest
        name: pytest (uv)
        entry: uv run pytest -q
        language: system
        pass_filenames: false
        stages: [pre-commit]
