repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.3
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        files: ^textual_cli_agent/
        pass_filenames: false
        additional_dependencies: [types-requests]
        args: [
          --ignore-missing-imports,
          -p,
          textual_cli_agent,
        ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: pytest
        name: pytest (uv)
        entry: bash -lc "uv run coverage run -m pytest -q && uv run coverage report --fail-under=40 -m"
        language: system
        pass_filenames: false
        stages: [pre-commit]
